# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: WETO Software Stack
author: Rafael Mudafort
logo: _images/logo.gif
copyright: '2023'
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/rafmudaf/wetostack
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  google_analytics_id: G-XK6LTW8XM7
  home_page_in_navbar: false

sphinx:
  mermaid_version: 10.1.0
  extra_extensions:
    - 'sphinxcontrib.mermaid'
  config:
    html_context:
      default_mode: light
