
name: deploy-pages

on:
  push:
    # branches:
    # - develop
    paths:
    - docs/**
  schedule:
    # https://crontab.guru/#00_00_*_*_2,4,6
    # "At 00:00 on Tuesday, Thursday, and Saturday."
    # Time zone for GitHub is UTC, so adjust accordingly; -6 in the summer, -7 in the winter.
    # Therefore, this runs at 6:00 PM Mountain Time on Monday, Wednesday, and Friday.
    - cron:  '00 00 * * 2,4,6'

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
        # pip install -e .

    # Build the book
    - name: Build the book
      working-directory: ${{runner.workspace}}/WETOStack/docs/
      run: |
        jupyter-book build .
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html